trigger:
  branches:
    include:
      - master
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'sqs-to-kafka'
  dockerfilePath: 'SqsToKafka/Dockerfile'
  solutionPath: 'SqsToKafka.sln'
  buildConfiguration: 'Release'

steps:
  # (Implicit) checkout happens automatically – no Checkout task needed

  # 1) Install .NET SDK
  - task: UseDotNet@2
    displayName: 'Install .NET SDK'
    inputs:
      packageType: 'sdk'
      version: '8.x'

  # 2) Restore
  - script: |
      dotnet restore $(solutionPath)
    displayName: 'dotnet restore'

  # 3) Build
  - script: |
      dotnet build $(solutionPath) --configuration $(buildConfiguration) --no-restore
    displayName: 'dotnet build'

  # 4) Test (will just say "0 tests" if you have none yet)
  - script: |
      dotnet test $(solutionPath) --configuration $(buildConfiguration) --no-build
    displayName: 'dotnet test'

  # 5) Install Docker CLI
  - task: DockerInstaller@0
    displayName: 'Install Docker CLI'

  # 6) Docker Build
  - script: |
      docker build -t $(imageName):$(Build.BuildId) -f $(dockerfilePath) .
    displayName: 'Docker build image'

  # 7) Save image to tar
  - script: |
      mkdir -p $(Build.ArtifactStagingDirectory)/images
      docker save $(imageName):$(Build.BuildId) \
        -o $(Build.ArtifactStagingDirectory)/images/$(imageName)-$(Build.BuildId).tar
    displayName: 'Save Docker image as tar'

  # 8) Copy K8s manifests
  - script: |
      mkdir -p $(Build.ArtifactStagingDirectory)/manifests
      cp k8s/k8s-sqskafka-config.yaml $(Build.ArtifactStagingDirectory)/manifests/
      cp k8s/k8s-sqskafka-deployment.yaml $(Build.ArtifactStagingDirectory)/manifests/
    displayName: 'Collect Kubernetes manifests'

  # 9) Publish artifacts
  - task: PublishBuildArtifacts@1
    displayName: 'Publish build artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
